### ISSUE TITLE
NetworkManager Broken with ViaVersion

### ISSUE THREAD

**Issue by HowardZHY** [HowardZHY/BurritoSpigot-Server#2]
[21:51:13 WARN]: Failed to initialize a channel. Closing: [id: 0x27ce6b18, L:/192.168.100.107:25562 - R:/192.168.100.108:59398]
java.lang.IllegalArgumentException: Duplicate handler name: via-encoder
        at io.netty.channel.DefaultChannelPipeline.checkDuplicateName(DefaultChannelPipeline.java:1055) ~[BurritoSpigot.jar:git-BurritoSpigot-"4c5d6b5"]
        at io.netty.channel.DefaultChannelPipeline.filterName(DefaultChannelPipeline.java:284) ~[BurritoSpigot.jar:git-BurritoSpigot-"4c5d6b5"]
        at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:247) ~[BurritoSpigot.jar:git-BurritoSpigot-"4c5d6b5"]
        at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:237) ~[BurritoSpigot.jar:git-BurritoSpigot-"4c5d6b5"]
        at com.viaversion.viaversion.bukkit.handlers.BukkitChannelInitializer.afterChannelInitialize(BukkitChannelInitializer.java:89) ~[?:?]
        at com.viaversion.viaversion.bukkit.handlers.BukkitChannelInitializer.initChannel(BukkitChannelInitializer.java:76) ~[?:?]
        at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:129) [BurritoSpigot.jar:git-BurritoSpigot-"4c5d6b5"]
        at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:112) [BurritoSpigot.jar:git-BurritoSpigot-"4c5d6b5"]
        at io.netty.channel.AbstractChannelHandlerContext.callHandlerAdded(AbstractChannelHandlerContext.java:938) [BurritoSpigot.jar:git-BurritoSpigot-"4c5d6b5"]
        at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:609) [BurritoSpigot.jar:git-BurritoSpigot-"4c5d6b5"]
        at io.netty.channel.DefaultChannelPipeline.access$100(DefaultChannelPipeline.java:46) [BurritoSpigot.jar:git-BurritoSpigot-"4c5d6b5"]
        at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1463) [BurritoSpigot.jar:git-BurritoSpigot-"4c5d6b5"]
        at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1115) [BurritoSpigot.jar:git-BurritoSpigot-"4c5d6b5"]
        at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:650) [BurritoSpigot.jar:git-BurritoSpigot-"4c5d6b5"]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:514) [BurritoSpigot.jar:git-BurritoSpigot-"4c5d6b5"]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.register(AbstractChannel.java:480) [BurritoSpigot.jar:git-BurritoSpigot-"4c5d6b5"]
        at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:87) [BurritoSpigot.jar:git-BurritoSpigot-"4c5d6b5"]
        at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:81) [BurritoSpigot.jar:git-BurritoSpigot-"4c5d6b5"]
        at io.netty.channel.MultithreadEventLoopGroup.register(MultithreadEventLoopGroup.java:86) [BurritoSpigot.jar:git-BurritoSpigot-"4c5d6b5"]
        at io.netty.bootstrap.ServerBootstrap$ServerBootstrapAcceptor.channelRead(ServerBootstrap.java:215) [BurritoSpigot.jar:git-BurritoSpigot-"4c5d6b5"]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [BurritoSpigot.jar:git-BurritoSpigot-"4c5d6b5"]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [BurritoSpigot.jar:git-BurritoSpigot-"4c5d6b5"]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [BurritoSpigot.jar:git-BurritoSpigot-"4c5d6b5"]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [BurritoSpigot.jar:git-BurritoSpigot-"4c5d6b5"]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [BurritoSpigot.jar:git-BurritoSpigot-"4c5d6b5"]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [BurritoSpigot.jar:git-BurritoSpigot-"4c5d6b5"]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [BurritoSpigot.jar:git-BurritoSpigot-"4c5d6b5"]
        at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:97) [BurritoSpigot.jar:git-BurritoSpigot-"4c5d6b5"]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722) [BurritoSpigot.jar:git-BurritoSpigot-"4c5d6b5"]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658) [BurritoSpigot.jar:git-BurritoSpigot-"4c5d6b5"]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584) [BurritoSpigot.jar:git-BurritoSpigot-"4c5d6b5"]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496) [BurritoSpigot.jar:git-BurritoSpigot-"4c5d6b5"]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [BurritoSpigot.jar:git-BurritoSpigot-"4c5d6b5"]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [BurritoSpigot.jar:git-BurritoSpigot-"4c5d6b5"]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_311]
[21:51:13 WARN]: An exception 'java.lang.NullPointerException' [enable DEBUG level for full stacktrace] was thrown by a user handler's exceptionCaught() method while handling the following exception:
java.lang.NullPointerException: null
        at net.minecraft.server.v1_8_R3.NetworkManager.close(NetworkManager.java:252) ~[BurritoSpigot.jar:git-BurritoSpigot-"4c5d6b5"]
        at net.minecraft.server.v1_8_R3.NetworkManager.channelInactive(NetworkManager.java:112) ~[BurritoSpigot.jar:git-BurritoSpigot-"4c5d6b5"]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) [BurritoSpigot.jar:git-BurritoSpigot-"4c5d6b5"]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) [BurritoSpigot.jar:git-BurritoSpigot-"4c5d6b5"]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241) [BurritoSpigot.jar:git-BurritoSpigot-"4c5d6b5"]
        at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:389) [BurritoSpigot.jar:git-BurritoSpigot-"4c5d6b5"]
        at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:354) [BurritoSpigot.jar:git-BurritoSpigot-"4c5d6b5"]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) [BurritoSpigot.jar:git-BurritoSpigot-"4c5d6b5"]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) [BurritoSpigot.jar:git-BurritoSpigot-"4c5d6b5"]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241) [BurritoSpigot.jar:git-BurritoSpigot-"4c5d6b5"]
        at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:389) [BurritoSpigot.jar:git-BurritoSpigot-"4c5d6b5"]
        at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:354) [BurritoSpigot.jar:git-BurritoSpigot-"4c5d6b5"]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) [BurritoSpigot.jar:git-BurritoSpigot-"4c5d6b5"]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) [BurritoSpigot.jar:git-BurritoSpigot-"4c5d6b5"]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241) [BurritoSpigot.jar:git-BurritoSpigot-"4c5d6b5"]
        at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:81) [BurritoSpigot.jar:git-BurritoSpigot-"4c5d6b5"]
        at io.netty.handler.timeout.IdleStateHandler.channelInactive(IdleStateHandler.java:277) [BurritoSpigot.jar:git-BurritoSpigot-"4c5d6b5"]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) [BurritoSpigot.jar:git-BurritoSpigot-"4c5d6b5"]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) [BurritoSpigot.jar:git-BurritoSpigot-"4c5d6b5"]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241) [BurritoSpigot.jar:git-BurritoSpigot-"4c5d6b5"]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405) [BurritoSpigot.jar:git-BurritoSpigot-"4c5d6b5"]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) [BurritoSpigot.jar:git-BurritoSpigot-"4c5d6b5"]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) [BurritoSpigot.jar:git-BurritoSpigot-"4c5d6b5"]
        at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901) [BurritoSpigot.jar:git-BurritoSpigot-"4c5d6b5"]
        at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:831) [BurritoSpigot.jar:git-BurritoSpigot-"4c5d6b5"]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) [BurritoSpigot.jar:git-BurritoSpigot-"4c5d6b5"]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) [BurritoSpigot.jar:git-BurritoSpigot-"4c5d6b5"]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) [BurritoSpigot.jar:git-BurritoSpigot-"4c5d6b5"]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [BurritoSpigot.jar:git-BurritoSpigot-"4c5d6b5"]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [BurritoSpigot.jar:git-BurritoSpigot-"4c5d6b5"]

**Comment by HowardZHY** [comment]
seems like not happen with latest autobuild
